### PR TITLE
Add support df_bit and rapid options for junos_ping

### PR DESCRIPTION
**Pull request by akira6592**
##### SUMMARY

Add support df_bit and rapid options for `junos_ping` module.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- `junos_ping`

### CODE REVIEW

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Review by rohitthakur2590 — APPROVED** [review]

**Comment by akira6592** [comment]
Should I fix something?

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
hitting command timeout.

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Pull request merged**
