### PR TITLE
Remove pretty_print  param from call  to_text

### PR DESCRIPTION
**Pull request by rohitthakur2590**
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
##### ISSUE TYPE

- Bugfix Pull Request
 

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by komaldesai13** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Review by komaldesai13 — APPROVED** [review]

**Pull request merged**
