### PR TITLE
Junos ACLs facts gathering firewall config fix

### PR DESCRIPTION
**Pull request by rohitthakur2590**
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>

##### SUMMARY

resolves: https://github.com/ansible-collections/junipernetworks.junos/issues/268

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
 
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rohitthakur2590** [comment]
recheck

**Review by justjais — APPROVED** [review]

**Comment by rohitthakur2590** [comment]
regate

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
regate

**Comment by gundalow** [comment]
Branch protections updated

**Pull request merged**
