### PR TITLE
docs updated after sanity fixes

### PR DESCRIPTION
**Pull request by rohitthakur2590**
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/619
##### SUMMARY

Docs updated after sanity fixes

##### ISSUE TYPE

 
- Docs Pull Request
 

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
opened separate PR https://github.com/ansible-collections/junipernetworks.junos/pull/86

**Comment by rohitthakur2590** [comment]
closed accedently

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
