### PR TITLE
Adding backup format functionality to junos_config module

### PR DESCRIPTION
**Pull request by kjspgd**
* Modified junos_config.py to allow specification of backup_format
  Valid backup formats include set, xml, json and text.
* Default is set, preserving previous first behavior.
* Updated plugins/module_utils/network/junos/junos.py tostring
  function to accept pretty_print argument, default is False.

##### SUMMARY

junos_config module backup functionality doesn't permit specification of format.
Created suboption under backup_options called backup_format, supporting
'set', 'text', 'xml' and 'json'.
In order to support formatted xml, updated tostring function of 
/module_utils/network/junos/junos.py to accept pretty_print argument.
Preserved defaults where possible.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/modules/junos_config.py
plugins/module_utils/network/junos/junos.py

##### ADDITIONAL INFORMATION

```
Before:
---
- name: Backup Junos
  hosts: 10.6.1.6
  gather_facts: no
  connection: local
  vars:
      backup_root: /playbooks/backups

  tasks:
    - name: get committed config
      junipernetworks.junos.junos_config:
         backup: true
         backup_options:
                 dir_path: "{{ backup_root }}"
                 filename: "{{ inventory_hostname }}"


After:
---
- name: Backup Junos
  hosts: 10.6.1.6
  gather_facts: no
  connection: local
  vars:
      backup_root: /playbooks/backups

  vars_prompt:
    - name: "TYPE"
      prompt: "Which Type output"
      private: no

  tasks:
    - name: get committed config
      junipernetworks.junos.junos_config:
         backup: true
         backup_options:
                 dir_path: "{{ backup_root }}"
                 filename: "{{ inventory_hostname }}.{{ TYPE }}"
                 backup_format: "{{ TYPE }}"


```

### CODE REVIEW

**Comment by surfer190** [comment]
Could I suggest using `format: "{{ TYPE }}"` instead of `backup_format`.
As this is already under the `backup_options` key.

**Comment by kjspgd** [comment]
> Could I suggest using `format: "{{ TYPE }}"` instead of `backup_format`.
> As this is already under the `backup_options` key.

This does make sense, but was trying to follow the convention set by 'src_format'

**Comment by kjspgd** [comment]
Inadvertantly closed with the comment.

**Comment by kjspgd** [comment]
It looks like the failing sanity checks are related to other, unrelated modules?

**Comment by kjspgd** [comment]
@rohitthakur2590 it looks like the tests failed due to other unrelated modules.  This is my first pull request; do I need to do anything further for review?

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
> @rohitthakur2590 it looks like the tests failed due to other unrelated modules. This is my first pull request; do I need to do anything further for review?

@kjspgd  Thank you for your contribution, Could you please add some tests as well.

**Comment by rohitthakur2590** [comment]
recheck

**Comment by kjspgd** [comment]
> > @rohitthakur2590 it looks like the tests failed due to other unrelated modules. This is my first pull request; do I need to do anything further for review?
> 
> @kjspgd Thank you for your contribution, Could you please add some tests as well.

Will do; I submitted a recheck now but will add some tests.

**Comment by rohitthakur2590** [comment]
recheck

**Comment by kjspgd** [comment]
Looks like passes?

**Comment by kjspgd** [comment]
@rohitthakur2590 Is there anything else I'd need to do here?

**Comment by rohitthakur2590** [comment]
> @rohitthakur2590 Is there anything else I'd need to do here?

@kjspgd  Thank you, This looks good for now, we gonna have this in the upcoming release.

**Pull request merged**
