### PR TITLE
Update documentation and add state for junos_acls

### PR DESCRIPTION
**Pull request by danielmellado**
This commit adds gathered state for junos_acls and updates the
documentation to the new resource modules versioning for collections.

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Comment by pabelanger** [comment]
Until we land job redesign, I am going to close this issue (and reopen) to free up some capacity.

**Pull request merged**
