### PR TITLE
Fix rollback implementation when value is 0

### PR DESCRIPTION
**Pull request by rohitthakur2590**
##### ISSUE TYPE

- Bugfix Pull Request
 

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by KB-perByte — APPROVED** [review]

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by komaldesai13** [comment]
recheck

**Comment by komaldesai13** [comment]
recheck

**Comment by komaldesai13** [comment]
recheck

**Comment by komaldesai13** [comment]
recheck

**Comment by komaldesai13** [comment]
recheck

**Comment by komaldesai13** [comment]
recheck

**Comment by komaldesai13** [comment]
recheck

**Comment by komaldesai13** [comment]
recheck

**Comment by komaldesai13** [comment]
recheck

**Pull request merged**
