### PR TITLE
Implement unlink in package installation

### PR DESCRIPTION
**Pull request by avermeer-tc**
##### SUMMARY
This implements the unlink option in package installations.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
junos_package

##### ADDITIONAL INFORMATION
This is particularly useful when trying to upgrade an EX2300 or EX3400. See https://supportportal.juniper.net/s/article/EX-Not-enough-storage-while-upgrading-Junos-EX2300-and-EX3400?language=en_US

This option is present in the Ansible Galaxy repository: https://galaxy.ansible.com/juniper/device

Duplicate of #397 which seems to have closed unexpectedly.

### CODE REVIEW

**Comment by Qalthos** [comment]
Can you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) to your PR? Thanks!

**Comment by avermeer-tc** [comment]
@Qalthos I've added the changelog item.

**Comment by avermeer-tc** [comment]
@rohitthakur2590 anything more needed here from my side?

**Comment by rohitthakur2590** [comment]
> @rohitthakur2590 anything more needed here from my side?

This looks good. Thank you very much!

**Review by rohitthakur2590 — APPROVED** [review]

**Pull request merged**
