### PR TITLE
[Junos]: docs updated

### PR DESCRIPTION
**Pull request by rohitthakur2590**
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>

##### ISSUE TYPE

 
- Feature Pull Request
 

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by pabelanger** [comment]
I am closing this, because I've noticed you are using this project directly for development. I would prefer if you fork this repo into your own namespace and create PRs against it.

**Pull request closed without merging**
