### PR TITLE
 Replace removed module._check_required_* calls

### PR DESCRIPTION
**Pull request by Qalthos**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

junos_logging

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Review by rohitthakur2590 — APPROVED** [review]

**Comment by rohitthakur2590** [comment]
rechek

**Comment by rohitthakur2590** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
