### PR TITLE
updated references of base plugins to netcommon

### PR DESCRIPTION
**Pull request by KB-perByte**
##### SUMMARY

Minimum required ansible.netcommon version is 2.5.1
Updated base plugin references to ansible.netcommon

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by Qalthos — CHANGES_REQUESTED** [review]

**Review by Qalthos — CHANGES_REQUESTED** [review]

**Review by Qalthos — APPROVED** [review]

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
regate

**Pull request merged**
