### PR TITLE
Use FQCN to M() references

### PR DESCRIPTION
**Pull request by bmillemathias**
##### SUMMARY
Use FQCN for the links
https://github.com/ansible-collections/overview/issues/89

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by acozine** [comment]
Looks good from a docs perspective. Thanks @bmillemathias!

**Review by rohitthakur2590 — APPROVED** [review]

**Review by ganeshrn — APPROVED** [review]

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
@bmillemathias  Thanks for the contribution! This looks good. Could you please add changelog fragments so that we can merge this.

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Pull request merged**
