### PR TITLE
Add resource module for junos acl interfaces

### PR DESCRIPTION
**Pull request by danielmellado**
This commit adds the resource module for managing filters/acls on
juniper devices

Signed-off-by: Daniel Mellado <dmellado@redhat.com>

### CODE REVIEW

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now fe228b41f312d042ec570e0dd74acd1e8ccf7fd3

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now e65f79189e751fcbda1f2f92e0b304778edef925

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 875135af49df4de9bbe58e6bc452656b6959116b

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now f97da415bce31acb5cf523b2f5d1b002c3199d01

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now de3bfd0a531878a63e48ad0e5750da706c88ba59

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 456d773a27919242db627d853a26dd47b19f689f

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 650e6cc3a4f27ff87f03270fd71dfb20d0522fbf

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 2af821cf3a4bdb5081c9831ae8780637d2c5fccf

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 96e1b72b8f24424299142b1915941109ddaeed7d

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 01cdda55173dacc1eac51cd73d867e7e1624c2f7

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now a69cc8d035170c75061d5162f40a1e5cf0ead3ba

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 88842f84d662b1f6acbf1240b478fbc5b627985d

**Comment by danielmellado** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by danielmellado** [comment]
recheck

**Pull request merged**
